### ISSUE TITLE
Error when uploading large images

### ISSUE THREAD

**Issue by khteo** [uraisg/media-library-azure#13]
We got an error when we tried to upload a 10mb image through the upload portal. No issue with smaller images.

![image0](https://user-images.githubusercontent.com/4019650/94251459-236efa00-ff55-11ea-8084-2d9a216aa24a.png)

@guangying94: Does Cognitive Services have a size limit on images that can be processed?

**Comment by guangying94** [comment]
Fixed by added a check on file size and recursive compression.
